version: '3.1'
services:
  davrods:
#    image: renci/docker-davrods:4.2.1
    image: davrods.docker:4.2.1
    depends_on:
      - irods
    build:
      context: ./4.2.1
      dockerfile: Dockerfile
    container_name: davrods
    hostname: davrods.local
    ports:
      - '8080:80'
      - '8443:443'
    networks:
      - davrods_local
    environment:
      - IRODS_CLIENT_SERVER_POLICY=CS_NEG_REFUSE
      - IRODS_SERVER_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
      - VHOST_SERVER_NAME=davrods.local
      - VHOST_LOCATION=/tempzone
      - VHOST_DAV_RODS_SERVER=irods 1247
      - VHOST_DAV_RODS_ZONE=tempZone
      - VHOST_DAV_RODS_AUTH_SCHEME=Native
      - VHOST_DAV_RODS_EXPOSED_ROOT=Zone
#      - SSL_ENGINE=on
#      - SSL_CERTIFICATE_FILE=/ssl_cert/star_renci_org.crt
#      - SSL_CERTIFICATE_KEY_FILE=/ssl_cert/star_renci_org.key
    restart: always
#    volumes:
#      - './4.2.1/davrods_conf.d:/etc/httpd/davrods_conf.d'
#      - './4.2.1/ssl_cert:/ssl_cert'

  irods:
    image: mjstealey/irods-provider-postgres:4.2.1
    container_name: irods
    hostname: irods.local
    networks:
      - davrods_local
    restart: always

  centos-davfs2:
    image: centos7:davfs2
    depends_on:
      - davrods
      - irods
    build:
      context: ./example/centos-davfs2
      dockerfile: Dockerfile
    container_name: centos-davfs2
    hostname: centos-davfs2.local
    privileged: true
    cap_add:
      - CAP_SYS_ADMIN
    devices:
      - /dev/fuse
    networks:
      - davrods_local
    environment:
      - LOCAL_MOUNT=/mnt/davrods
      - DAVRODS_MOUNT=http://davrods/tempzone
      - DAVRODS_USERNAME=rods
      - DAVRODS_PASSWORD=rods
    restart: always

  ubuntu-davfs2:
    image: ubuntu16.04:davfs2
    depends_on:
      - davrods
      - irods
    build:
      context: ./example/ubuntu-davfs2
      dockerfile: Dockerfile
    container_name: ubuntu-davfs2
    hostname: ubuntu-davfs2.local
    privileged: true
    cap_add:
      - CAP_SYS_ADMIN
    devices:
      - /dev/fuse
    networks:
      - davrods_local
    environment:
      - LOCAL_MOUNT=/mnt/davrods
      - DAVRODS_MOUNT=http://davrods/tempzone
      - DAVRODS_USERNAME=rods
      - DAVRODS_PASSWORD=rods
    restart: always

networks:
  davrods_local: